version: 3

tasks:
  generate:
    aliases:
      - gen
    desc: "generate go files using protobuf contract"
    cmds:
      - protoc -I ./proto ./proto/filemanager.proto --go_out=./gen/go --go_opt=paths=source_relative --go-grpc_out=./gen/go --go-grpc_opt=paths=source_relative

  default:
    - task generate